name: eyer8
favicon: null
layout_spectrum: 0.18479
typography_spectrum: 0.5605
title: Not eyer8 at all
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbffff'
    - '#ff0000'
    - '#000000'
    - '#880100'
    - '#652f2a'
  brandStrength: 0.3125
  lightness: 0.4908755354117602
  saturation: 0.5585623241495341
  rhythmicContrast: 0.7550117215141654
purpose: []
