typography_spectrum: 0.5605
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#b20000'
    - '#f6d705'
    - '#6b6b6b'
  brandStrength: 0.3125
  lightness: 0.4908755354117602
  saturation: 0.5585623241495341
  rhythmicContrast: 0.7550117215141654
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.18479
analytics:
  google: null
  facebook: null
  twitter: null
name: eyer8
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: jkjkjkj
purpose: []
